import { SaleObjectType } from '@/types/SaleObjectTypes/SaleObjectType';

export const saleObjectData: SaleObjectType[] = [
  {
    id: '1',
    image_url: '/img/items/item1.png',
    name: 'Cà rốt',
    net_weight: '100',
    unit: 'g',
    quantity: 1,
    price: 5000,
    starRank: 4.5,
    reviews: 25,
  },
  {
    id: '2',
    image_url: '/img/items/item1.png',
    unit: 'g',
    quantity: 2,
    net_weight: '200',
    name: 'Cải thảo',
    price: 10000,
    starRank: 3.5,
    reviews: 10,
  },
  {
    id: '3',
    image_url: '/img/items/item1.png',
    unit: 'g',
    quantity: 5,
    net_weight: '150',
    name: 'Cải xoong',
    price: 8000,
    starRank: 4,
    reviews: 15,
  },
  {
    id: '4',
    image_url: '/img/items/item2.png',
    unit: 'g',
    quantity: 1,
    net_weight: '100',
    name: 'Củ cải trắng',
    price: 6000,
    starRank: 4,
    reviews: 20,
  },
  {
    id: '5',
    image_url: '/img/items/item3.png',
    unit: 'g',
    quantity: 2,
    net_weight: '200',
    name: 'Củ đậu',
    price: 12000,
    starRank: 3.5,
    reviews: 5,
  },
  {
    id: '6',
    image_url: '/img/items/item4.png',
    unit: 'g',
    quantity: 1,
    net_weight: '250',
    name: 'Dưa chuột',
    price: 7000,
    starRank: 4.5,
    reviews: 30,
  },
  {
    id: '7',
    image_url: '/img/items/item5.png',
    unit: 'g',
    quantity: 1,
    net_weight: '200',
    name: 'Hành tây',
    price: 10000,
    starRank: 4,
    reviews: 18,
  },
  {
    id: '8',
    image_url: '/img/items/item1.png',
    unit: 'g',
    quantity: 1,
    net_weight: '150',
    name: 'Rau cải',
    price: 5000,
    starRank: 3.2,
    reviews: 7,
  },
  {
    id: '9',
    image_url: '/img/items/item1.png',
    unit: 'g',
    quantity: 1,
    net_weight: '100',
    name: 'Rau muống',
    price: 3000,
    starRank: 4,
    reviews: 12,
  },
  {
    id: '10',
    image_url: '/img/items/item1.png',
    unit: 'g',
    quantity: 1,
    net_weight: '200',
    name: 'Cà chua',
    price: 7000,
    starRank: 4.5,
    reviews: 22,
  },
];
