import { SaleObjectComboType } from '@/types/SaleObjectTypes/SaleObjectComboType';

export const saleObjectComboData: SaleObjectComboType[] = [
  {
    id: '1',
    name: 'Combo cơm trưa 1',
    image_url: '/img/items/item1.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '2',
    name: 'Combo cơm trưa 2',
    image_url: '/img/items/item2.png',
    isConfirm: true,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '3',
    name: 'Combo cơm trưa 3',
    image_url: '/img/items/item3.png',
    isConfirm: true,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '4',
    name: 'Combo cơm trưa 4',
    image_url: '/img/items/item4.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '5',
    name: 'Combo cơm trưa 5',
    image_url: '/img/items/item5.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '6',
    name: 'Combo cơm trưa 6',
    image_url: '/img/items/item6.png',
    isConfirm: true,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '7',
    name: 'Combo cơm trưa 7',
    image_url: '/img/items/item7.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '8',
    name: 'Combo cơm trưa 8',
    image_url: '/img/items/item8.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '9',
    name: 'Combo cơm trưa 9',
    image_url: '/img/items/item9.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
  {
    id: '10',
    name: 'Combo cơm trưa 10',
    image_url: '/img/items/item10.png',
    isConfirm: false,
    items: [
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
      {
        image_url: '/img/items/item1.png',
        name: 'Cà rốt',
        quantity: 1,
        net_weight: 100,
        unit: 'g',
      },
    ],
  },
];
